// Generated by scripts/build-browser-traits.mjs
export const TRAIT_VALUE_DICTIONARY=["egfreid"];
export const TRAIT_ROWS=[[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[0,0],[],[],[],[],[],[]];
